### ISSUE TITLE
Add the ability to catch errors from event listeners via ExceptionFilters

### ISSUE THREAD

**Issue by Jake13f** [nestjs/event-emitter#1175]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to be able to use NestJS `ExceptionFilters` with event listeners the same way they can be used on controllers with rest endpoints.

### Describe the solution you'd like

I would like to be able to use exception filters like the following on a controller and have it also filter exceptions that were thrown in the Event Emitter Listeners.

```ts
@Catch()
export class MyEventExceptionFilter implements ExceptionFilter {
  catch(exception: unknown, host: ArgumentsHost) {
    // Handle error
  }
}

@Controller()
@UseFilters(MyEventExceptionFilter)
export class MySubscriptionController {
  @OnEvent("MY_EVENT")
  onEvent() {
    // This should be able to be filtered
    throw new Error('')
  }
}
```

### What is the motivation / use case for changing the behavior?

It would be nice to be able to catch certain things happening more cleanly using this approach and be more consistent the way Nestjs handles rest controller errors.

**Comment by micalevisk** [comment]
I like the ideia but I don't think that this is feasible

I'd have to investigate it further tho

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

This has been discussed in the past and we decided to not implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
