### ISSUE TITLE
Event listeners are registered twice

### ISSUE THREAD

**Issue by adelbke** [nestjs/event-emitter#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I have not managed to run the events in the repl. I try to trigger them in the repl by using the eventEmitter instance from the dependency injection mechanism but failed to do so. I created a new repo to test this and turns out there's something wrong. Here's a detailed overview

## in my codebase (`@nestjs/core v9`):

I have EventEmitter.forRoot({ global: true }) imported in `app.module.ts` only

I added this method to the app.service.ts which is directly declared as a provider in app.module.ts only

in the repl I try
`get(EventEmitter2)` I get an error, the token doesn't exist
`get(EventEmitter)` works but the event emitter is empty the result of that get is this
```typescript
EventEmitter {
  _events: {},
  _newListener: false,
  _removeListener: false,
  verboseMemoryLeak: false
}
```
I set the newListener option to `true` and tried this again to check if this one would reflect the change and it didn't work
I got creative and tried this:

`get(EventSubscribersLoader).eventEmitter` and it works ! I recognize all my events registered on my app.
I try emitting an event and it works BUT the eventHandler is ran twice ? I blame it on my self, maybe I am wrong because the handler was in a dynamic module

I add a method to the `app.service.ts` which is only provided in `app.module.ts`
```typescript

@Injectable()
export class AppService {
	constructor(eventEmitter: EventEmitter2) {
		console.log('AppModuleInit');
		console.log(eventEmitter);
	}
	getHello(): string {
		return 'Hello World!';
	}

	@OnEvent('testevent', { async: true, promisify: true })
	async test() {
		console.log('test text');
	}
}
```
I emit `testevent` like this:
`await get(EventSubscribersLoader).eventEmitter.emitAsync('testevent')`

I get this
```
test text
test text
[ undefined, undefined ]
```

I reproduced this in a different repo linked below,  same error

## in the reproduction repo (`@nestjs/core v10`):

App.service.ts

```typescript
import { Injectable } from '@nestjs/common';
import { OnEvent } from '@nestjs/event-emitter';


@Injectable()
export class AppService {

  @OnEvent('testEvent', { promisify: true, async: true })
  getHello(): string {
    return 'Hello World!';
  }
}
```

getting the eventEmitter directly works for some reason
```
> get(EventEmitter)
EventEmitter {
  _events: { testEvent: [ [Function], [Function] ] },
  _newListener: false,
  _removeListener: false,
  verboseMemoryLeak: false,
  _conf: { global: true }
}
```
BUT again !

```
> await get(EventEmitter).emitAsync('testEvent')
[ 'Hello World!', 'Hello World!' ]
```

### Minimum reproduction code

https://github.com/adelbke/event-emitter-duplicate-events-reproduction

### Expected behavior

Every event emitted once should trigger listeners once and once only !

### Package version

"^2.0.2" in my codebase "^2.0.4" in the reproduction repo

### NestJS version

"^9.0.11" in my codebase "^10.0.0" in the reproduction repo

### Node.js version

v16.14.2 tested also with node v18.12.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by adelbke** [comment]
Update:

I have found why `get(EventEmitter)` didn't work in my codebase, I had two eventEmitter instances running in my app.
I found the bug and fixed it Now `get(EventEmitter)` works in my codebase ^^

But the problem persists , the listener is still triggered twice

**Comment by micalevisk** [comment]
it works when you drop the useless `NestFactory.createApplicationContext(AppModule)` call. I can't tell for sure if this is expected or a bug regarding sharing the same root module on both `repl` and `NestFactory.create*`

![image](https://github.com/nestjs/event-emitter/assets/13461315/7008f4d2-c4cf-44b4-ae65-53070cc8fa2e)

side note: please next time make sure that your repro has everything to reproduce the issue. It lacks a npm-script to run the repl file

**Comment by micalevisk** [comment]
@adelbke I'm in the same boat as you. I'd have to investigate deeper to understand how that was possible. 

I guess you can create a new issue at the main repo to report this as a `repl` issue(?) then we will see Kamil thoughts about it
