### ISSUE TITLE
Durable event subscribers

### ISSUE THREAD

**Issue by firmbase-tal** [nestjs/event-emitter#1247]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I would like to create durable request scoped event subscribers.  
From what I saw in the documentation, request scoped event subscribers shouldn't be supported: https://docs.nestjs.com/techniques/events#:~:text=WARNING,be%20request%2Dscoped.
Looking at the code I do see support for it though through the `registerRequestScopedListener` function in `event-subscribers-loader.ts`
Currently, the request scoped subscriber version generates a context id, instead of using the context id strategy.

### Describe the solution you'd like

I would like a durable version for the given loader. Meaning one that relies on the context id strategy instead of generating a context id automatically.

### Teachability, documentation, adoption, migration strategy

```
@Injectable({ scope: Scope.REQUEST, durable: true })
export class MyDurableInjectable() {
    @OnEvent('my-event')
    private async myEventHandler(event: any) {
        ...
    }
}
```

### What is the motivation / use case for changing the behavior?

My app uses durable providers, I would like to create event subscribers in those providers and have them remain durable.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by firmbase-tal** [comment]
Sure thing.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/1248
