### ISSUE TITLE
Emit event decorator

### ISSUE THREAD

**Issue by AnandChowdhary** [nestjs/event-emitter#3]
Would be a great addition to have a decorator to emit an event, for example in a controller.

In [staart/api](https://github.com/staart/api), I have a decorator [`@AuditLog`](https://github.com/staart/api/blob/master/src/modules/domains/domains.controller.ts#L31) which is called like so:

```ts
@Controller('domains')
export class DomainController {
  constructor() {}
  @Post()
  @AuditLog('create-domain')
  async create() {
    return { ok: true }
  }
}
```

Similarly, we could do:

```ts
@Controller('domains')
export class DomainController {
  constructor() {}
  @Post()
  @EmitEvent('domain-created', new CreateDomainEvent())
  async create(): Promise<{ ok: boolean }> {
    return { ok: true }
  }
}
```

In this example, the event will be dispatched in the function doesn't throw an error. With this use case, I can replace my audit logger with an event emitter! 😄

**Comment by kamilmysliwiec** [comment]
@AnandChowdhary `EventEmitter` is registered within Nest IoC container and so there's no way to access it outside of the application context (e.g., from within the decorator). Anyway, you should be able to achieve what you proposed with `@SetMetadata` + global interceptor :)
