### ISSUE TITLE
Make event name avaliable

### ISSUE THREAD

**Issue by incompletude** [nestjs/event-emitter#379]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm trying to catch all my events and log them all by name and payload:

This gives undefined:

```
  @OnEvent("**")
  public handleEverything(parentId: number): void {
    // log all events by event name
    // @ts-expect-error this.event
    console.log(this.event)
  }
```

This doesn't get called:

```
  public constructor(private readonly eventEmitter: EventEmitter2) {
    this.eventEmitter.on("**", function (value1, value2) {
      // @ts-expect-error this.event
      console.log(this.event)
    })
  }
```

### Describe the solution you'd like

Somehow have access to the event name.

### What is the motivation / use case for changing the behavior?

Avoid lots of boilerplate.

**Comment by micalevisk** [comment]
instead of

https://github.com/nestjs/event-emitter/blob/398e4f58ff2e2288d1ed293126fa2ede4931da49/lib/event-subscribers.loader.ts#L60-L64

we could have this:

```ts
this.eventEmitter.on( 
 event, 
 function onEventHandlerCore(...args: unknown[]) {
    instance.event = this.event;
    return instance[methodKey].call(instance, ...args);
 }, 
 options, 
); 
```

then we can access the event on `this.event` on `handleEverything` method. But to me this approach doesn't seems good for NestJS.

I don't know how the interface for this feature would look like :/

**Comment by micalevisk** [comment]
an ideia: `@nestjs/event-emitter` should provide a parameter decorator (like the `@Query()` and `@Body()` ones) that will always be the last event handled

```ts
  @OnEvent("**")
  public handle(payload: any, @Event() event: any): void {
    console.log(event)
  }
```

But I don't know how reliable and feasible is this.

**Comment by kamilmysliwiec** [comment]
Use `emitter.onAny(listener)` instead. https://www.npmjs.com/package/eventemitter2
