### ISSUE TITLE
Support eventemitter2.prependListener() as an alternative for registering subscribers

### ISSUE THREAD

**Issue by Drew-Kimberly** [nestjs/event-emitter#401]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'd like to have some control over the ordering of event listeners. My general feature request is to provide an option such that I can ensure a given listener registered with the `OnEvent` decorator is fired before another listener.

### Describe the solution you'd like

I'd like the `OnEvent` decorator options to support an interface similar to:
```typescript
type OnEventOptions = OnOptions & { prependListener?: boolean }
```

`prependListener` will default to `false`. In `EventSubscribersLoader`, the new config value will be respected and register the decorated subscriber via:
- `on` when `prependListener` is `false`
- `prependListener` when `prependListener` is `true`

eventemitter2 ref: https://github.com/EventEmitter2/EventEmitter2#emitterprependlistenerevent-listener-options

### Teachability, documentation, adoption, migration strategy

This feature will be backwards-compatible as the new configuration option is optional and defaults to `false`.

### What is the motivation / use case for changing the behavior?

I'd like to ensure that a given decorator event subscriber is always triggered first.

**Comment by Drew-Kimberly** [comment]
> Would you like to create a PR for this feature?

Happy to! Should be able to get around to it next week

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/418
