### ISSUE TITLE
The event listener is called twice.

### ISSUE THREAD

**Issue by boy672820** [nestjs/event-emitter#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Creating a standalone application calls the event listener multiple times.

### Minimum reproduction code

https://github.com/boy672820/nest-event/blob/main/src/main.ts#L6

### Expected behavior

const app = await NestFactory.create(AppModule);
const standalone = await NestFactory.createApplicationContext(AppModule);
const bupService = standalone.get(BupService);

bupService.subscribeTransfer();

### Package version

^1.0.0

### In which operating systems have you tested?

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Your code is incorrect.

Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
