### ISSUE TITLE
Events are not emitted when I use "onModuleInit" for testing purposes

### ISSUE THREAD

**Issue by felinto-dev** [nestjs/event-emitter#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Events are not emitted when I use "onModuleInit" for testing purposes

```ts
@Injectable()
export class AppService implements OnModuleInit {
  constructor(private eventEmitter: EventEmitter2) {}

  onModuleInit() {
    this.getHello();
  }

  getHello(): string {
    const message = 'Emitting event in AppService->getHello()';
    console.log('get hello was trigged!');
    this.eventEmitter.emit('message', message);
    console.log(this.eventEmitter.listeners());
    return message;
  }

  @OnEvent('message')
  async onMessageReceived(payload: string) {
    console.log('showing payload', payload);
  }
}
```

The method "getHello" emits an event and this event is logged in the terminal. I am using "onModuleInit" for testing purposes and to check if everything is working but the event is not emitted when I use "onModuleInit". If I try to do a REST request to `localhost:3000` everything works well! 

### Minimum reproduction code

https://github.com/felinto-dev/nestjs-event-emitter-issue

### Steps to reproduce

1. yarn
2. yarn start:dev
3. Check the terminal console
4. Send a GET request to http://localhost:3000
5. Check the terminal console
6. Check the file `src/app.service.ts` to play around and debug this issue

### Expected behavior

The event should be emitted no matter whether I use `onModuleInit` or send a REST API request.

### Package version

1

### NestJS version

8

### Node.js version

16

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Event listeners are wired up in the `onApplicationBootstrap` hook https://github.com/nestjs/event-emitter/blob/master/lib/event-subscribers.loader.ts#L22 (which runs after `onModuleInit()`)
