### ISSUE TITLE
Subscriber Trigger Multiple time on OnEvent Decorator

### ISSUE THREAD

**Issue by totalard** [nestjs/event-emitter#493]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

The Following Listener Triggered 2 Time on a single Emit

```
  @OnEvent('order.failed')   
  handleOrderFailed(payload: any) {
    console.log(payload);
  }
```

Where as the below works currectly,

```
@Injectable()
export class GlobalSubscriber {
  constructor(private eventEmitter: EventEmitter2) {
    this.eventEmitter.on('**', (payload) => {
      console.log(payload);
    });
  }

}
```

Seems BUG, please Verify

i chnaged OS, also run same in server ubuntu, but still it trigger 2 time, i getting console.log 2 time in console.

### Minimum reproduction code

https://github.com/nestjs/nest/tree/master/sample/30-event-emitter

### Steps to reproduce

npm i

### Expected behavior

The Event Subscriber should trigger only 1 time, and not Multiple time

### Package version

1.1.1

### NestJS version

8.4.4

### Node.js version

14+

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
