### ISSUE TITLE
@OnEvent decorators is not working when applied multiple times on same method

### ISSUE THREAD

**Issue by mentos1386** [nestjs/event-emitter#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Doing something like should work:

```ts
@Injectable()
class Service {

  @OnEvent('event.one')
  @OnEvent('event.two')
  private twoEventsOnOneMethod(data: any) {
    // ...
  }
}
```

As it should roughly translate to two `.on` calls on event emitter2:

```ts
eventEmitter2.on('event.one', () => service.twoEventsOnOneMethod)
eventEmitter2.on('event.two', () => service.twoEventsOnOneMethod)
```

But it doesn not. It only uses one of the `OnEvent` instead of all.

### Minimum reproduction code

https://github.com/mentos1386/nestjs-events-on-event-issue

### Steps to reproduce

1. `npm i`
2. `npm start`
3. `curl http://localhost:3000/`

### Expected behavior

In the logs, we would expect to see "hello from event one" and "hello from event two'. But only one will be present.

### Package version

1.1.1

### NestJS version

8.4.7

### Node.js version

v16.15.1

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [X] Linux

### Other

Reference to issue that touches this topic https://github.com/nestjs/event-emitter/issues/52#issuecomment-768942667

**Comment by Maligosus** [comment]
The second decorator call overrides EVENT_LISTENER_METADATA. That is way one subscription will be called.

**Comment by kamilmysliwiec** [comment]
This is the expected behavior.
