### ISSUE TITLE
Multiple event types not handled (impossible to)

### ISSUE THREAD

**Issue by NtTestAlert** [nestjs/event-emitter#654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Passing an array to `OnEvent` does not work, and that might be intended behavior but is not mentioned anywhere in the docs.
That being said there is currently no way to handle multiple events using this module. Multiple `@OnEvent` would overwrite previous metadata.

The bug report https://github.com/nestjs/event-emitter/issues/596 was just closed stating that indeed this does not work. (While using wildcards is viable in some cases, it is not in others)

Is this intentional and there is an important reason why this behavior is made impossible? Fixing this should be very simple, by simply changing the way metadata is stored to hold an array of settings, and on initialization walk the array. For less confusion in decorators and backwards compatibility, `@OnEvents` could be added, that would explicitly suggest that the array input will be treated as separate events. Should I open a PR for adding this functionality?

This is something that can be done in an hours time or less, and currently one needs to resort to:

```
@Injectable()
export class GenericListener implements OnApplicationBootstrap {
  constructor(
    private readonly eventEmitter: EventEmitter2,
  ) {}

  onApplicationBootstrap() {
    const callback = (event: EventData) =>
      this.handleGenericEvent(event);
    const events = [
      EVENT_ONE,
      EVENT_TWO
      EVENT_THREE,
    ];
    for (const event of events) {
      this.eventEmitter.on(event, callback);
    }
  }
```

### Minimum reproduction code

provided in issue

### Expected behavior

```
@OnEvents([
  EVENT_ONE,
  EVENT_TWO,
  EVENT_THREE,
])
async handleGenericEvent(event: EventData) {
```

or

```
@OnEvent(EVENT_ONE)
@OnEvent(EVENT_TWO)
@OnEvent(EVENT_THREE)
async handleGenericEvent(event: EventData) {
```

work as one would expect

### Package version

master

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Maligosus** [comment]
#596 it's not events array. Its namespace delimiter.

**Comment by NtTestAlert** [comment]
> [#596 it's not events array. Its namespace delimiter.](https://github.com/nestjs/event-emitter/issues/596#issuecomment-1259220037)

Indeed, but currently it is **impossible** to react to multiple events, because using multiple `@OnEvent` overwrites the decorator metadata.
One would need to either create a separate wrapper method for every event type (which would become unmaintainable with many events or dynamic arrays), or use EventEmitter2 directly (which defeats the purpose of the library). 

Instead the decorator metadata could be implemented in a way that handled that gracefully.

Not always will events that we want to handle conform to something that can be solved with wildcards

**Comment by pklaschka** [comment]
I generally speaking hate "+1" comments, but quickly wanted to say that this capability would significantly improve my developer experience with this library.

I don't have a strong opinion about multiple `OnEvent()` vs a single `OnEvents()` decorator (although I will say that it just took me some time trying to figure out that my intuitive attempt of using multiple `OnEvent()` decorators wasn't supported, so if that continues to be unsupported, clear documentation about this would be great), but if one of these options gets added to this library, that will make my day (on whatever day it gets released) 😉 (and enable much cleaner code for these kinds of scenarios).

For now, I'm glad to have found at least a working solution (thanks, @NtTestAlert , for sharing that workaround), but I would greatly appreciate not having to explicitly inject the event emitter into my services just for that.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/657
