### ISSUE TITLE
Custom event decorators break with the latest array metadata type requirement

### ISSUE THREAD

**Issue by davidzwa** [nestjs/event-emitter#751]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When using a custom event decorator an error is thrown: `eventListenerMetadatas is not iterable`. After digging it is clear that the latest release `1.4.1` and specifically this PR https://github.com/nestjs/event-emitter/pull/657 causes it.

### Minimum reproduction code

https://github.com/davidzwa/nest-event-bug/actions/runs/4292223946/jobs/7478397448

### Steps to reproduce

1) Create a custom decorator https://github.com/davidzwa/nest-event-bug/blob/main/src/custom-event.decorator.ts
2) Register it https://github.com/davidzwa/nest-event-bug/blob/9d616087d86bac5adbe0fac929eb373e180572bf/src/app.service.ts#L6

See MR repo workflow for the error https://github.com/davidzwa/nest-event-bug/actions/runs/4292223946/jobs/7478397448

### Expected behavior

The array type should either be enforced with the return type of the decorator (now using generic `MethodDecorator`) or **preferably** it should rather be backwards compatible and allow non-array event metadata to work without failure.

Undesirable alternative:
The error `eventListenerMetadatas is not iterable` should be prevented and clarified.

Takeaway: the return type at https://github.com/nestjs/event-emitter/blob/f9667ae391eb47c17ab855d10ae6514ceb1876a6/lib/events-metadata.accessor.ts#L13 is not enforced at build time.

### Package version

1.4.1

### NestJS version

^9.0.0

### Node.js version

18.14.2

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [X] Linux

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/760
