### ISSUE TITLE
Jest Unit tests only emit events when intializing full AppModule

### ISSUE THREAD

**Issue by DanielMenke** [nestjs/event-emitter#770]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I assemble a`TestingModule` which does not resemble the full `AppModule`, my event listeners don't get registered at the EventEmitter

With this code:
```typescript
const module: TestingModule = await Test.createTestingModule({
      imports: [EventEmitterModule.forRoot()],
      providers: [RecipesService, EventEmitter2],
    }).compile()
   
const app = await module.createNestApplication();
await app.init();
```
the events don't work,

If I initialize the complete AppModule like this:

```typescript
 const module: TestingModule = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();

 const app = await module.createNestApplication();
 await app.init();
```   
the events work fine. 

this is my `AppModule`: 
 
```typescript
 @Module({
  imports: [
    EventEmitterModule.forRoot(),
    RecipesModule,
  ]
})
export class AppModule {}

```
    

### Minimum reproduction code

-

### Steps to reproduce

`yarn test`

### Expected behavior

Events should be emitted and listened to in both scenarios

### Package version

1.4.1

### NestJS version

8.4.7

### Node.js version

18.10.0

### In which operating systems have you tested?

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by Maligosus** [comment]
Token `EventEmitter2` not initialized provider. EventEmitterModule.forRoot() initialize provider by token `EventEmitter2` and return EventEmitter2 instance.

**Comment by kamilmysliwiec** [comment]
Please provide a [minimum reproduction repository](https://minimum-reproduction.wtf/) (Git repository/[StackBlitz](https://stackblitz.com/fork/github/nestjs/typescript-starter)/[CodeSandbox](https://codesandbox.io/s/github/nestjs/typescript-starter/tree/master) project).

**Comment by DanielMenke** [comment]
@kamilmysliwiec 

Its my bad. 

The problem is that by putting `EventEmitter2` in the providers list, the emitter provided by `EventEmitterModule.forRoot()` gets overwritten by a new EventEmitter2 instance without any listeners. Sorry for opening this as a bug.

**Comment by t36campbell** [comment]
@DanielMenke Thank you so much for following up on this. I did the exact same thing in my event service and it was driving me nuts for days

**Comment by rohitk-globant** [comment]
@DanielMenke if possible can provide a snippet on how I can use it. I'm trying to a scenario where once the event gets triggered I want to test if the functions registered with `@OnEvent` gets called. I'm kind of stuck it would be nice if you can provide some snippet on how do did it since my mocks are not emitting the events as well as they don't have any listeners attached to them.

**Comment by DanielMenke** [comment]
@BruceWayneTheSupermanSlayer I did it as shown above, with the slight difference that I didn't list the EventEmitter2 class inside my TestingModules provider-Array.

```
const module: TestingModule = await Test.createTestingModule({
      imports: [EventEmitterModule.forRoot()],
      providers: [RecipesService],
    }).compile()
```
   

INSTEAD OF 
```

const module: TestingModule = await Test.createTestingModule({
      imports: [EventEmitterModule.forRoot()],
      providers: [RecipesService, EventEmitter2],
    }).compile()
   
```

**Comment by DanielMenke** [comment]
I simply use my actual implementation inside my test case and only mock the parts that I don't really care about in the test scenario. Do you mock the parts of your implementation which call the emit functions?
