### ISSUE TITLE
Provider EventEmitter can't not resolve when using TerserPlugin webpack

### ISSUE THREAD

**Issue by doonpy** [nestjs/event-emitter#790]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Build nestJS application with @nwrl/webpack using `optimization: true`. It'll change name of `EventEmitter` class name so DI container can't resolve this provider.
The root cause may be `EventEmitter` is a function not a class.

This is config of TerserPlugin of @nwrl/webpack
```js
new TerserPlugin({
                parallel: true,
                terserOptions: {
                  keep_classnames: true,
                  ecma: 2020,
                  safari10: true,
                  output: {
                    ascii_only: true,
                    comments: false,
                    webkit: true,
                  },
                },
              })
```

### Minimum reproduction code

none

### Expected behavior

DI container can resolve `EventEmitter` provider

### Package version

1.4.1

### NestJS version

9.1.4

### Node.js version

16.x

### In which operating systems have you tested?

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by Maligosus** [comment]
Class name is `EventEmitter2`

**Comment by doonpy** [comment]
> Class name is `EventEmitter2`

Sorry my fault
Actually I use class name is EventEmitter2

**Comment by doonpy** [comment]
Sorry, I forgot import `EventEmitterModule` in `AppModule`
