### ISSUE TITLE
Using event emitter in imported npm package cannot resolve emitter

### ISSUE THREAD

**Issue by twilker** [nestjs/event-emitter#869]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Simply add a module that is included in a npm package to the app that contains a service that consumes the `EventEmitter2` service.

This lead to this error
```
Error: Nest can't resolve dependencies of the PackageService (?). Please make sure that the argument EventEmitter at index [0] is available in the PackageModule context.
```

Instead, when I import the module directly it works as expected.

### Minimum reproduction code

https://github.com/twilker/nest-event-bug-app

### Steps to reproduce

1. Clone Minimum reproduction code repository
2. Execute on `main` branch to see wrong behavior
3. Execute on `working` branch to see expected bahavior

### Expected behavior

It should be possible to use it in npm packages as the purpose is to separate modules better by loose coupling. In order to facilitate the separation it is obvious to wish to split the nest app into multiple separately versioned npm packages and consume it in a single nest app.

### Package version

1.4.2

### NestJS version

9.4.3

### Node.js version

18.12.1

### In which operating systems have you tested?

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by micalevisk** [comment]
it should be `EventEmitterModule.forRoot()` here:

![image](https://github.com/nestjs/event-emitter/assets/13461315/f2ba7114-916a-4b62-8ee7-c4530a5622ea)

**Comment by twilker** [comment]
This was just a test to see if I can get it to work like this. The `forRoot` call can be found in the AppModule
![image](https://github.com/nestjs/event-emitter/assets/2802526/df0f6e23-957a-4f01-9e70-fc6db5fd08d2)
I can remove the import in the `PackageModule` and it still works in the `working` branch and not in the `main` branch.

If I change it to `forRoot` I get another error:
```
Error: Nest can't resolve dependencies of the EventSubscribersLoader (DiscoveryService, EventEmitter, EventsMetadataAccessor, MetadataScanner, ?). Please make sure that the argument ModuleRef at index [4] is available in the EventEmitterModule context.
```

Again it works both with or without the import in the `PackageModule` when using directly. But that is not my desired solution.

**Comment by kamilmysliwiec** [comment]
Please, use our [Discord](https://discord.gg/G7Qnnhy) channel (support) for such questions. We are using GitHub to track bugs, feature requests, and potential improvements.
