### ISSUE TITLE
Upgrade to use event emitter 3, or add an option for it 

### ISSUE THREAD

**Issue by vvtri** [nestjs/event-emitter#878]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

no

### Describe the solution you'd like

Upgrade to use event emitter 3, or add an option for it 

### What is the motivation / use case for changing the behavior?

Event emitter 3 is faster, not use nodeJs event.

**Comment by kamilmysliwiec** [comment]
Thanks for your suggestion!

There are no plans to implement it in the foreseeable future.

If you think your request could live outside Nest's scope, we'd encourage you to collaborate with the [community](https://discord.gg/G7Qnnhy) on publishing it as an open source package.
