### ISSUE TITLE
Option to throw error if an event fails to process

### ISSUE THREAD

**Issue by klutzer** [nestjs/event-emitter#934]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

The new version of event-emitter 2.0.1 suppress all errors by default, as described here: https://github.com/nestjs/event-emitter/issues/932. As the thread was closed, I'd like to suggest a way to keep the old behavior, because we can't update to the new version, since getting the errors when a event is unprocessed is crucial for us.

### Describe the solution you'd like

It'd be nice if we can just include a property `suppressErrors` in `EventEmitterModule` or in `OnEvent` so it will be possible to get errors from failed listeners. Without that, probably we'll have to stuck with the 2.0.0 version.

### What is the motivation / use case for changing the behavior?

The main goal is to get the erros thrown by the decorated `OnEvent` methods. This option could be deactivated by default (since the default now is to suppress all errors), but with an option to use the last behavior (`suppressErrors: false`), since that's very important for our projects.

**Comment by kamilmysliwiec** [comment]
Would you like to create a PR for this issue?

**Comment by klutzer** [comment]
Sure, I'll open as soon as I can.

**Comment by kamilmysliwiec** [comment]
Let's track this here https://github.com/nestjs/event-emitter/pull/936
