### ISSUE TITLE
Add OnSafeEvent

### ISSUE THREAD

**Issue by koreanddinghwan** [nestjs/event-emitter#994]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

OnEvent has problem with server stops.

### Describe the solution you'd like

```ts
import { applyDecorators, Logger } from '@nestjs/common';
import { OnEvent, OnEventType } from '@nestjs/event-emitter';
import { OnEventOptions } from '@nestjs/event-emitter/dist/interfaces';

function _OnSafeEvent() {
  return function (target: any, key: string, descriptor: PropertyDescriptor) {
    const originalMethod = descriptor.value;

    const metaKeys = Reflect.getOwnMetadataKeys(descriptor.value);
    const metas = metaKeys.map((key) => [key, Reflect.getMetadata(key, descriptor.value)]);

    descriptor.value = async function (...args: any[]) {
      try {
        await originalMethod.call(this, ...args);
      } catch (err) {
        Logger.error(err, err.stack, 'OnSafeEvent');
      }
    };
    metas.forEach(([k, v]) => Reflect.defineMetadata(k, v, descriptor.value));
  };
}

export function OnSafeEvent(event: OnEventType, options?: OnEventOptions | undefined) {
  return applyDecorators(OnEvent(event, options), _OnSafeEvent());
}

```

### What is the motivation / use case for changing the behavior?

do not stop server when the exception not catched in OnEvent

**Comment by micalevisk** [comment]
So you're basically proposing a no-op on  errors for event handlers.

What about adding a new option to the `OnEvent` instead. Both aren't that flexible tho...

**Comment by koreanddinghwan** [comment]
> So you're basically proposing a no-op on errors for event handlers.
> 
> What about adding a new option to the `OnEvent` instead. Both aren't that flexible tho...

```ts
import { OnOptions } from 'eventemitter2';
export declare type OnEventOptions = OnOptions & {
    prependListener?: boolean;
    suppressErrors?: boolean;
};
```

is suppressErrors do the samething as i suggested?

**Comment by micalevisk** [comment]
yes. I didn't know about that flag

https://github.com/nestjs/event-emitter/blob/0c5b4048ec0325ef65866c46362ea51192dab0e4/tests/e2e/module-e2e.spec.ts#L136C94-L145

**Comment by koreanddinghwan** [comment]
thank you, 
in korea, i saw a blog about 'when event handler do not catch exception, server stops with runtime error'  
[blogs](https://velog.io/@loakick/Nest.js-event-emitter%EC%97%90%EB%9F%AC-Error%EA%B0%80-%EB%B0%9C%EC%83%9D%ED%95%98%EB%A9%B4)

but, i cannot reproduce that behavior.

or, somewhere in

i've already make 'onSafeEvent' decorator in my project, but... should it needed?

i think that if we wanna  **log eventHandler's exception** , then use the custom decorator is fine.

oh, i found PR #936

**Comment by micalevisk** [comment]
@koreanddinghwan the docs is missing that feature as well

feel free to open a PR to update it https://docs.nestjs.com/techniques/events

**Comment by koreanddinghwan** [comment]
> @koreanddinghwan the docs is missing that feature as well
> 
> feel free to open a PR to update it https://docs.nestjs.com/techniques/events

got it, i'm not good at open-source contribute, and it will be the first time, but i'll gonna try it, thank you for your help!

**Comment by koreanddinghwan** [comment]
https://github.com/nestjs/docs.nestjs.com/pull/2888
